language: node_js
node_js:
  - "node"
before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
deploy: 
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  provider: npm
  on:
    tags: true
env:
  global:
    secure: V09LiODOa40r0NjFH2bz0XTZL1KDsDqwMf1c4/tOGtO8/Hzj5ws3y7focvFdLyAwU6BibibnFV3Z7kw5EwPoIYpYBSgkckPNVpMBGgUf90zVigaMFeZBlEaa1xRdoXhlvs8xmtsZvw6wO9a6f8aekYIqJBtLviR09ByuYUkR0DHMyeEae4TXYOflpTu6SEUOgGJbAd68+UhivvTohxeAeF94vdx0WVReiiKnGlrASV+hE9o163Sf/eADZ88h8PkdpxrMntHt+Z8J5S6VCrVM3YCFNqtM6ChNCIDz+QfyLXKq7a1VBh2peDYTceCpHTa5+w6K+G6Rlj72PYwb++8IJUwabl/w8eN6554A8wLrRfEBVAV3bMkXcwry35FhWlQ65VS4nJyf31I94KSWZNzyRQlU8mI/YDLAVrI6PmoSZ+g4bKhCdWdab6tZOIhFaYVeUn+OwJxqSizHIEcUIGvArfytsPw06KWTNgJVrWqim0rFeL8qNb+TpbHneY9WvZ0MXj9SU1nWVS7KM66NgcVGvYyDT+PN2kgwHqDswzki/GX0KyZCWE9wBGX0MApIx0OnB7wSKdxH8YB1Z+CZB1sRX43qQ1QNxPQobmNFBNJhObbVpUrI2UnXqW1xQl2AFpqFFbKKjr+dNebGLDDEdF2NUoydwd6qD4yc3F1SsPpTRUo=
# safelist 
branches:
  only:
  - master